version: 2
jobs:
  build:
    docker:
      - image: docker:17
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
  node8:
    docker:
      - image: node:8-alpine
    steps:
      - run: apk add --no-cache make bash git ca-certificates
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "yarn.lock" }}
          - node8-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
  node9:
    docker:
      - image: node:9-alpine
    steps:
      - run: apk add --no-cache make bash git ca-certificates
      - checkout
      - restore_cache:
          keys:
          - node9-dependencies-{{ checksum "yarn.lock" }}
          - node9-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node9-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
workflows:
  version: 2
  build:
    jobs:
      - build
      - node8
      - node9
